/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rubricbasedevaluation;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JTable;

/**
 *
 * @author Azeem Hashmi
 */
public class StudentForm extends javax.swing.JFrame {

    String action;
    String name;
    Student std;
    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
    }
    
    public StudentForm(String Action, String Name) {
        initComponents();
        StudentTableModel table = new StudentTableModel(StudentInfo.getSInstance().getAllStudent());
         
        jTable1.setModel(table);
        
         Action increase = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int row = Integer.valueOf(e.getActionCommand());
                StudentTableModel model = (StudentTableModel) table.getModel();
                model.editRow(row);     
            }
        };
        ButtonColumn inc = new ButtonColumn(jTable1, increase, 5);
        
       
         Action deleteAction = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int row = Integer.valueOf(e.getActionCommand());
                StudentTableModel model = (StudentTableModel) table.getModel();
                model.deleteRow(row);     
            }
        };
        ButtonColumn deleteButton = new ButtonColumn(jTable1, deleteAction, 6);
       
        
        this.action = Action;
        this.name = Name;
        
        if (action.equals("Add"))
        {
           std = new Student(); 
        }
        
        else if (action.equals("Edit"))
        {
            jLabel1.setText("Update Student Info");
            regBtn.setText("Update");
            
            std = StudentInfo.getSInstance().getStudent(name);
            nameField.setText(std.getName());
            emailField.setText(std.getEmail());
            cityField.setText(std.getCity());
            deptField.setText(std.getDept());
            regField.setText(std.getRegNo());
            pwdField.setText(std.getPassword());
            userField.setText(std.getUsername());
        }
        
        else if (action.equals("Delete"))
        {
            jLabel1.setText("Delete Teacher Info");
            regBtn.setText("Delete");
            
            Student s = StudentInfo.getSInstance().getStudent(name);
            this.std = s;
            nameField.setText(std.getName());
            emailField.setText(std.getEmail());
            cityField.setText(std.getCity());
            deptField.setText(std.getDept());
            regField.setText(std.getRegNo());
            pwdField.setText(std.getPassword());
            userField.setText(std.getUsername());
            
            nameField.setEditable(false);
            emailField.setEditable(false);
            cityField.setEditable(false);
            deptField.setEditable(false);
            regField.setEditable(false);
            pwdField.setEditable(false);
            userField.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        regField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dobField = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        deptField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        regBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pwdField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 61, 89));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_40px.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(229, 229, 220));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Student Registration");

        jLabel2.setText("Name");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");

        jLabel4.setText("Reg #");

        jLabel5.setText("Gender");

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel6.setText("DOB");

        jLabel7.setText("City");

        jLabel8.setText("Department");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_back_arrow_20px.png"))); // NOI18N
        jButton1.setText("Back to Main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        regBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_check_document_20px.png"))); // NOI18N
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Username");

        jLabel10.setText("Password");

        pwdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jButton1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userField)
                            .addComponent(cityField)
                            .addComponent(dobField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameField)
                            .addComponent(emailField)
                            .addComponent(regField)
                            .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deptField)
                            .addComponent(pwdField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(regField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Student Regitration", jPanel2);

        jPanel3.setBackground(new java.awt.Color(229, 229, 220));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Student Registration");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Record", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminMenu am = new AdminMenu();
        am.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        // TODO add your handling code here:
        if (action.equals("Edit"))
        {
            String Name = nameField.getText();
            String Email = emailField.getText();
            String Gender = genderCombo.getSelectedItem().toString();
            SimpleDateFormat ssdf = new SimpleDateFormat("yyyy-MM-dd");
            String Date = ssdf.format(dobField.getDate());
            String City = cityField.getText();
            String Dept = deptField.getText();
            String RegNo = regField.getText();
            String Username = userField.getText();
            String Pwd = pwdField.getText();

            int count1 = 0;

            if (strValid(Name)) 
            {
                jLabel12.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel12.setForeground(Color.BLACK);
                jLabel12.setText("Valid");
                count1++;
            } 
            else 
            {
                jLabel12.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel12.setForeground(Color.RED);
                jLabel12.setText("Invalid");
            }

            if (emailValid(Email))
            {
                jLabel13.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel13.setForeground(Color.BLACK);
                jLabel13.setText("Valid");
                count1++;
            }
            else 
            {
                jLabel13.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel13.setForeground(Color.RED);
                jLabel13.setText("Invalid");
            }

            if (regNoValid(RegNo))
            {
                jLabel14.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel14.setForeground(Color.BLACK);
                jLabel14.setText("Valid");
                count1++;
            }
            else
            {
                jLabel14.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel14.setForeground(Color.RED);
                jLabel14.setText("Invalid");
            }

            if (strValid(City))
            {
                jLabel15.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel15.setForeground(Color.BLACK);
                jLabel15.setText("Valid");
                count1++;
            }
            else
            {
                jLabel15.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel15.setForeground(Color.RED);
                jLabel15.setText("Invalid");
            }

            if (strValid(Dept))
            {
                jLabel16.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel16.setForeground(Color.BLACK);
                jLabel16.setText("Valid");
                count1++;
            }
            else
            {
                jLabel16.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel16.setForeground(Color.RED);
                jLabel16.setText("Invalid");
            }

            if (usernameValid(Username))
            {
                jLabel17.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel17.setForeground(Color.BLACK);
                jLabel17.setText("Valid");
                count1++;
            }
            else
            {
                jLabel17.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel17.setForeground(Color.RED);
                jLabel17.setText("Invalid");
            } 

            if (pwdValid(Pwd))
            {
                jLabel18.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel18.setForeground(Color.BLACK);
                jLabel18.setText("Valid");
                count1++;
            }
            else
            {
                jLabel18.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel18.setForeground(Color.RED);
                jLabel18.setText("Invalid");
            }

            if (count1 == 7)
            {
                Student std1 = new Student();
                std1.setName(Name);
                std1.setCity(City);
                std1.setEmail(Email);
                std1.setGender(Gender);
                std1.setDOB(Date);
                std1.setDept(Dept);
                std1.setRegNo(RegNo);
                std1.setPassword(Pwd);
                std1.setUsername(Username);
                StudentInfo.getSInstance().updateStudent(name,std1);
            }
        }
        
        else if (action.equals("Delete"))
        {
            StudentInfo.getSInstance().deleteStudent(name);
        }
        
        else if (action.equals("Add"))
        {
            String name = nameField.getText();
            String email = emailField.getText();
            String gender = genderCombo.getSelectedItem().toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(dobField.getDate());
            String city = cityField.getText();
            String dept = deptField.getText();
            String regNo = regField.getText();
            String username = userField.getText();
            String pwd = pwdField.getText();

            int count = 0;

            if (strValid(name)) 
            {
                jLabel12.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel12.setForeground(Color.BLACK);
                jLabel12.setText("Valid");
                count++;
            } 
            else 
            {
                jLabel12.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel12.setForeground(Color.RED);
                jLabel12.setText("Invalid");
            }

            if (emailValid(email))
            {
                jLabel13.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel13.setForeground(Color.BLACK);
                jLabel13.setText("Valid");
                count++;
            }
            else 
            {
                jLabel13.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel13.setForeground(Color.RED);
                jLabel13.setText("Invalid");
            }

            if (regNoValid(regNo))
            {
                jLabel14.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel14.setForeground(Color.BLACK);
                jLabel14.setText("Valid");
                count++;
            }
            else
            {
                jLabel14.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel14.setForeground(Color.RED);
                jLabel14.setText("Invalid");
            }

            if (strValid(city))
            {
                jLabel15.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel15.setForeground(Color.BLACK);
                jLabel15.setText("Valid");
                count++;
            }
            else
            {
                jLabel15.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel15.setForeground(Color.RED);
                jLabel15.setText("Invalid");
            }

            if (strValid(dept))
            {
                jLabel16.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel16.setForeground(Color.BLACK);
                jLabel16.setText("Valid");
                count++;
            }
            else
            {
                jLabel16.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel16.setForeground(Color.RED);
                jLabel16.setText("Invalid");
            }

            if (usernameValid(username))
            {
                jLabel17.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel17.setForeground(Color.BLACK);
                jLabel17.setText("Valid");
                count++;
            }
            else
            {
                jLabel17.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel17.setForeground(Color.RED);
                jLabel17.setText("Invalid");
            } 

            if (pwdValid(pwd))
            {
                jLabel18.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel18.setForeground(Color.BLACK);
                jLabel18.setText("Valid");
                count++;
            }
            else
            {
                jLabel18.setFont(new Font("Times New Roman", Font.PLAIN, 11));
                jLabel18.setForeground(Color.RED);
                jLabel18.setText("Invalid");
            }

            if (count == 7)
            {
                Student std1 = new Student();
                std1.setName(name);
                std1.setCity(city);
                std1.setEmail(email);
                std1.setGender(gender);
                std1.setDOB(date);
                std1.setDept(dept);
                std1.setRegNo(regNo);
                std1.setPassword(pwd);
                std1.setUsername(username);

                StudentInfo.getSInstance().addStudent(std1);
                //System.out.print(TeacherInfo.getTInstance().teacherList.get(0).getName());
            }
        }
    }//GEN-LAST:event_regBtnActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void pwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }
    
    public boolean strValid(String str)
    {
        for (int i=0 ; i<str.length() ; i++)
        {
            if (!((str.charAt(i) >= 'A' && str.charAt(i) <= 'Z') || (str.charAt(i) >= 'a' && str.charAt(i) <= 'z') || (str.charAt(i) == ' ')))
            {
                return false;
            }
        }
        return true;
    }
    
    public boolean usernameValid(String username)
    {
        boolean flag = false;
        if (username.length() == 20)
        {
            if (username.charAt(0) >= '0' && username.charAt(0) <= '9')
            {
                if (username.charAt(1) >= '0' && username.charAt(1) <= '9')
                {
                    if (username.charAt(2) >= '0' && username.charAt(2) <= '9')
                    {
                        if (username.charAt(3) >= '0' && username.charAt(3) <= '9')
                        {
                            //if (username.charAt(4) == '-' && username.charAt(7) == '-')
                            {
                                if (username.charAt(4) >= 'a' && username.charAt(4) <= 'z')
                                {
                                    if (username.charAt(5) >= 'a' && username.charAt(5) <= 'z')
                                    {
                                        if (username.charAt(6) >= '0' && username.charAt(6) <= '9')
                                        {
                                            if (username.charAt(7) >= '0' && username.charAt(7) <= '9')
                                            {
                                                if (username.charAt(8) >= '0' && username.charAt(8) <= '9')
                                                {
                                                    if (username.charAt(9) == '@')
                                                    {
                                                        if ((username.charAt(10) == 'u') && (username.charAt(11) == 'e') && (username.charAt(12) == 't'))
                                                        {
                                                            if ((username.charAt(13) == '.') && (username.charAt(14) == 'e') && (username.charAt(15) == 'd') && (username.charAt(16) == 'u'))
                                                            {
                                                                if ((username.charAt(17) == '.') && (username.charAt(18) == 'p') && (username.charAt(19) == 'k'))
                                                                {
                                                                    flag = true;
                                                                    return true;
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        
        if (flag == true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    
    public boolean pwdValid(String str)
    {
        boolean flag = false;
        if (str.length() >= 8)
        {
            for (int i=0 ; i<str.length() ; i++)
            {
                if ((str.charAt(i) >= 'A' && str.charAt(i) <= 'Z') || (str.charAt(i) >= 'a' && str.charAt(i) <= 'z') || (str.charAt(i) >= '0' && str.charAt(i) <= '9'))
                {
                    flag = true;
                }
                else
                {
                    return false;
                }
            }
        }
        
        if (flag == true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    
    public boolean emailValid(String email)
    {
        boolean flag = false;
        int index = -1, count = 0;
        
        for (int i=0; i<email.length(); i++)
        {
            if (email.charAt(i) == '@')
            {
                index = i;
                count++;
            }
        }
        
        if (count == 1)
        {
            int size = email.length();
            
            for (int i=0; i<size; i++)
            {
                if (email.charAt(size-4) == '.' && email.charAt(size-3) == 'c')
                {
                    if (email.charAt(size-2) == 'o' && email.charAt(size-1) == 'm')
                    {
                        flag = true;
                    }
                }
            }
        }
        
        if (flag == true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    
    public boolean regNoValid (String regNo)
    {
        boolean flag = false;
        if (regNo.length() == 11)
        {
            if (regNo.charAt(0) >= '0' && regNo.charAt(0) <= '9')
            {
                if (regNo.charAt(1) >= '0' && regNo.charAt(1) <= '9')
                {
                    if (regNo.charAt(2) >= '0' && regNo.charAt(2) <= '9')
                    {
                        if (regNo.charAt(3) >= '0' && regNo.charAt(3) <= '9')
                        {
                            if (regNo.charAt(4) == '-' && regNo.charAt(7) == '-')
                            {
                                if (regNo.charAt(5) >= 'A' && regNo.charAt(5) <= 'Z')
                                {
                                    if (regNo.charAt(6) >= 'A' && regNo.charAt(6) <= 'Z')
                                    {
                                        if (regNo.charAt(8) >= '0' && regNo.charAt(8) <= '9')
                                        {
                                            if (regNo.charAt(9) >= '0' && regNo.charAt(9) <= '9')
                                            {
                                                if (regNo.charAt(10) >= '0' && regNo.charAt(10) <= '9')
                                                {
                                                    flag = true;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        
        if (flag == true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField deptField;
    private com.toedter.calendar.JDateChooser dobField;
    private javax.swing.JTextField emailField;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField pwdField;
    private javax.swing.JButton regBtn;
    private javax.swing.JTextField regField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
